version: '3.9'

services:
  zbx_db:
    image: mariadb:10.11
    container_name: zbx_db
    hostname: zbx_db
    restart: always
    environment:
      #MARIADB_ROOT_PASSWORD: rootpwd
      MYSQL_ROOT_PASSWORD: rootpwd
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"

  zbx_sv:
    build: ./zbx_sv
    container_name: zbx_sv
    hostname: zbx_sv
    restart: always
    ports:
      - 10051:10051
      - 162:162/udp
    environment:
      TZ: 'Asia/Tokyo'
    depends_on:
      - zbx_db

  zbx_web:
    build: ./zbx_web
    container_name: zbx_web
    hostname: zbx_web
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: 'Asia/Tokyo'
    depends_on:
      - zbx_db
      - zbx_sv

